[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
epplex_program = "AESTfYJoYvW7Wp2yTkbRJU8GZxKHeV8wPDzU3cFHULuL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
